name: travel
description: "A Travel Restaurant booking App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Depedencies
  cupertino_icons: ^1.0.6
  http:
  shared_preferences:
  connectivity_plus:
  cached_network_image:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
